// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv15tqfWJGDPvJH9bS4iL_rsJ-5vFTUTo',
    appId: '1:555735212656:web:31b1fc49d0f3c9e3e6cab5',
    messagingSenderId: '555735212656',
    projectId: 'flutter-keep-56b29',
    authDomain: 'flutter-keep-56b29.firebaseapp.com',
    storageBucket: 'flutter-keep-56b29.appspot.com',
    measurementId: 'G-M3R3NT9D4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd5j17SphyHoBr7_sp4Qgu6eP3HYPMfow',
    appId: '1:555735212656:android:b23c528e6cff679ee6cab5',
    messagingSenderId: '555735212656',
    projectId: 'flutter-keep-56b29',
    storageBucket: 'flutter-keep-56b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZE7QnOpnpO00UzJmQH3tjArpcSazp1jQ',
    appId: '1:555735212656:ios:0e78ec478238963ce6cab5',
    messagingSenderId: '555735212656',
    projectId: 'flutter-keep-56b29',
    storageBucket: 'flutter-keep-56b29.appspot.com',
    iosClientId: '555735212656-ihe3alts2mjhgbvl91oijcatkuinbfhp.apps.googleusercontent.com',
    iosBundleId: 'dev.flutterKeep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZE7QnOpnpO00UzJmQH3tjArpcSazp1jQ',
    appId: '1:555735212656:ios:0e78ec478238963ce6cab5',
    messagingSenderId: '555735212656',
    projectId: 'flutter-keep-56b29',
    storageBucket: 'flutter-keep-56b29.appspot.com',
    iosClientId: '555735212656-ihe3alts2mjhgbvl91oijcatkuinbfhp.apps.googleusercontent.com',
    iosBundleId: 'dev.flutterKeep',
  );
}
